#!/bin/sh
#

daemon="/usr/local/sbin/dnsblock"
daemon_flags="server -v"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_start() {
	${rcexec} "${daemon} ${daemon_flags} > /var/log/dnsblock 2>&1 ${_bg}"
}

rc_cmd $1
